CREATE TABLE [dbo].[tbl_Subscribers] (
    [Id]   INT           NOT NULL IDENTITY,
	[Key] UNIQUEIDENTIFIER NOT NULL,
    [Name]         NVARCHAR (64) NOT NULL,
    [Class] NVARCHAR(64) NOT NULL,
    [Level] INT NOT NULL, 
    [Background] NVARCHAR(64) NOT NULL, 
    [PlayerName] NVARCHAR(64) NOT NULL, 
    [Race] NVARCHAR(64) NOT NULL, 
    [Alignment] NVARCHAR(64) NOT NULL, 
    [Experience] INT NOT NULL, 
    [Strength] INT NOT NULL, 
    [Dexterity] INT NOT NULL, 
    [Constitution] INT NOT NULL, 
    [Intelligence] INT NOT NULL, 
    [Wisdom] INT NOT NULL, 
    [Charisma] INT NOT NULL, 
    [Inspiration] INT NOT NULL, 
    [ProficiencyBonus] INT NOT NULL, 
    [ArmorClass] INT NOT NULL, 
    [Initiative] INT NOT NULL, 
    [Speed] INT NOT NULL, 
    [HitPointMaximum] INT NOT NULL, 
    [CurrentHitPoints] INT NOT NULL, 
    [TemporaryHitPoints] INT NULL, 
    [TotalHitDice] NVARCHAR(5) NOT NULL, 
    [HitDice] NVARCHAR(5) NOT NULL, 
    [SuccessDeathSaves] INT NOT NULL, 
    [FailedDeathSaves] INT NOT NULL, 
    [PersonalityTraits] NVARCHAR(256) NULL, 
    [Ideals] NVARCHAR(256) NULL, 
    [Bonds] NVARCHAR(256) NULL, 
    [Flaws] NVARCHAR(256) NULL, 
    [PassiveWisdom] INT NOT NULL, 
    [Age] INT NOT NULL, 
    [Height] NVARCHAR(10) NOT NULL, 
    [Weight] NVARCHAR(10) NOT NULL, 
    [Eyes] NVARCHAR(20) NOT NULL, 
    [Skin] NVARCHAR(20) NOT NULL, 
    [Hair] NVARCHAR(20) NOT NULL, 
    [SpellcastingClass] NVARCHAR(64) NULL, 
    [SpellcastingAbility] INT NULL, 
    [SpellSaveDC] INT NULL, 
    [SpellAttackBonus] INT NULL, 
    [AppearanceKey] UNIQUEIDENTIFIER NULL, 
    [Backstory] NVARCHAR(MAX) NULL, 
    PRIMARY KEY CLUSTERED ([Id] ASC), 
	CONSTRAINT [AK_5eCharacters_NoDuplicates] UNIQUE ([Key]) 
);

